sudo: false
language: php
dist: trusty

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.npm
        - node_modules

php:
    - 7.2
    - 7.3

before_install:
    - composer create-project --prefer-dist chinloyal/lavuet MyApp
    - nvm install 13.7
    - npm i -g npm

install:
    - cd MyApp
    - npm install

script:
    - npm run dev

notifications:
    email: false
