version: '3.7'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        container_name: phpmyadmin-demo
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        restart: always
        links:
            - db:mysql
    db:
        image: mysql:8
        container_name: mysql-demo
        command:
            [
                '--character-set-server=utf8mb4',
                '--collation-server=utf8mb4_unicode_ci',
                '--default-authentication-plugin=mysql_native_password',
            ]
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=demo
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - ./data:/var/lib/mysql
